<?php
/**
 * Smart Theme
 *
 * @author      Pavel Panchyshnyy
 * @category    design
 * @package     smart_theme
 */
?>
<?php
/**
 * Currency switcher
 *
 * @var Mage_Directory_Block_Currency $this
 */
?>
<?php
$current_code = $this->getCurrentCurrencyCode();
$current_symbol = $this->getCurrentCurrencySymbol($current_code);
?>

<?php if ($this->getCurrencyCount() > 1): ?>
    <div class="header-form currency">
        <div class="title" title="<?php echo $this->__('Select Currency') ?>">
        <span>
            <?php echo $this->__('Currency: ') ?>
            <span class="current"><?php echo $current_symbol . ' ' . $current_code ?></span>
        </span>
            <span class="mobile-close"></span>
        </div>
        <ul class="switch-options">
            <?php foreach ($this->getCurrencies() as $_code => $_symbol): ?>
                <?php if ($_code == $current_code) {
                    continue;
                } ?>
                <li class="switcher" onclick="setLocation('<?php echo $this->getSwitchCurrencyUrl($_code) ?>')">
                    <span><?php echo $_symbol . ' ' . $_code ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
