<?php
/**
 * Smart Theme
 *
 * @author      Pavel Panchyshnyy
 * @category    design
 * @package     smart_theme
 */
/**
 * Shoping cart sidebar
 *
 * @var Mage_Checkout_Block_Cart_Sidebar $this
 */
?>

<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>

<div class="header-minicart-wrapper">
    <a href="<?php echo $this->helper('checkout/cart')->getCartUrl(); ?>" class="skip-link skip-cart <?php if($_cartQty <= 0): ?> no-count<?php endif; ?>">
        <i class="fa fa-shopping-bag fa-2x" aria-hidden="true"></i>
        <span class="label"><?php echo $this->__('Cart'); ?></span>
        <span class="count"><?php echo $_cartQty; ?></span>
    </a>

    <div class="header-minicart-content">
        <?php echo $this->getChildHtml('minicart_content');?>
    </div>
</div>
