<?php
/**
 * Smart Theme
 *
 * @author      Pavel Panchyshnyy
 * @category    design
 * @package     smart_theme
 */
?>
<div class="footer-container" data-scroll-class="zoomIn" data-img="<?php echo $this->getSkinUrl('images/slider/slide_1.jpg')?>">
    <div class="footer">
        <?php //echo $this->getChildHtml() ?>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
</div>
