<?php
/**
 * Smart Theme
 *
 * @author      Pavel Panchyshnyy
 * @category    design
 * @package     smart_theme
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="mobile-header">
    <span id="mobile-header"></span>
</div>

<!-- Cart -->
<div class="header-minicart">
    <?php echo $this->getChildHtml('minicart_head'); ?>
</div>

<header id="header" class="page-header">
    <div class="header-container">
        <div class="header-top">
            <div class="container">
                <a class="logo" href="<?php echo $this->getUrl('') ?>">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                    <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
                </a>
                <!-- Hover Links -->
                <div class="hover-links">
                    <div class="hover-wrapper account">
                        <a class="hover-link">
                            <span class="icon"></span>
                            <span class="label"><?php echo $this->__('Account'); ?></span>
                        </a>
                        <!-- Account -->
                        <div id="header-account" class="hover-content">
                            <?php echo $this->getChildHtml('topLinks') ?>
                            <div class="header-select-block">
                                <?php echo $this->getChildHtml('store_language') ?>
                                <?php echo $this->getChildHtml('currency_switcher') ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-main"></div>
        <div class="header-bottom">
            <?php echo $this->getLayout()->getBlock('footer.before')->toHtml() ?>
            <?php echo $this->getLayout()->getBlock('footer')->toHtml() ?>
        </div>
    </div>
</header>