<?php
/**
 * Smart Theme
 *
 * @author      Pavel Panchyshnyy
 * @category    design
 * @package     smart_theme
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="mobile-header">
    <span id="mobile-header"></span>
</div>

<header id="header" class="page-header">
    <div class="header-container">
        <div class="header-top">
            <div class="container">
                <a class="logo" href="<?php echo $this->getUrl('') ?>">
                    <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="large" />
                    <img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" class="small" />
                </a>
                <div class="header-select-block">
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('currency_switcher') ?>
                </div>
                <!-- Skip Links -->
                <div class="skip-links">
                    <a href="#header-nav" class="skip-link skip-nav">
                        <span class="icon"></span>
                        <span class="label"><?php echo $this->__('Menu'); ?></span>
                    </a>

                    <a href="#header-search" class="skip-link skip-search">
                        <span class="icon"></span>
                        <span class="label"><?php echo $this->__('Search'); ?></span>
                    </a>

                    <div class="account-cart-wrapper">
                        <a href="<?php echo $this->helper('customer')->getAccountUrl(); ?>" data-target-element="#header-account" class="skip-link skip-account">
                            <span class="icon"></span>
                            <span class="label"><?php echo $this->__('Account'); ?></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-main"></div>
        <div class="header-bottom">
            <?php echo $this->getLayout()->getBlock('footer.before')->toHtml() ?>
            <?php echo $this->getLayout()->getBlock('footer')->toHtml() ?>
        </div>
    </div>
</header>